### ISSUE TITLE
Can u please resolve these errors

### ISSUE THREAD

**Issue by nitishkumarnitc** [selem1/login-form-angular2#1]
ERROR in [default] /home/nitish/web_components/loginFormAngular2/node_modules/@types/jasmine/index.d.ts:39:37 
A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [default] /home/nitish/web_components/loginFormAngular2/node_modules/@types/jasmine/index.d.ts:39:45 
Cannot find name 'keyof'.

ERROR in [default] /home/nitish/web_components/loginFormAngular2/node_modules/@types/jasmine/index.d.ts:39:51 
'=' expected.

ERROR in [default] /home/nitish/web_components/loginFormAngular2/src/app/login/loginService/authenticate.service.ts:24:35 
Argument of type 'UserComponent' is not assignable to parameter of type 'string'.

**Comment by selemxmn** [comment]
Fixed + update `package.json` to new libraries ! Thanks for reporting.
